version: "3.9"
services:
  eureka-server:
    container_name: eureka-server
    hostname: eureka-server
    build:
      context: ./eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 2s
      timeout: 3s
      retries: 30

  apigateway:
    container_name: apigateway
    hostname: apigateway
    build:
      context: ./apigateway
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy

  db-tickets:
    container_name: db-tickets
    hostname: db-tickets
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 2s
      timeout: 3s
      retries: 30

  ms-tickets:
    container_name: ms-tickets
    hostname: ms-tickets
    build:
      context: ./ms-tickets
    ports:
      - "8089:8089"
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka
      - TICKETS_MYSQL_URL=jdbc:mysql://db-tickets:3306/tickets?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - TICKETS_MYSQL_USER=root
      - TICKETS_MYSQL_PASSWORD=root
    depends_on:
      eureka-server:
        condition: service_healthy
      db-tickets:
        condition: service_healthy
  ms-market:
    container_name: ms-market
    hostname: ms-market
    build:
      context: ./Market_MS
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka
      - TICKETS_MYSQL_URL=jdbc:mysql://db-tickets:3306/tickets?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - TICKETS_MYSQL_USER=root
      - TICKETS_MYSQL_PASSWORD=root
    depends_on:
      eureka-server:
        condition: service_healthy
      db-tickets:
        condition: service_healthy

  nodejs-app:
    container_name: nodejs-app
    build:
      context: ./stripe-ms
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      eureka-server:
        condition: service_healthy

  db-nest:
    hostname: db-nest
    image: bitnami/mongodb:latest
    restart: always
    environment:
      - MONGODB_USERNAME=nest
      - MONGODB_PASSWORD=nest
      - MONGODB_DATABASE=nest
      - MONGODB_ROOT_PASSWORD=nest
    ports:
      - "27019:27017"
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      timeout: 5s
      retries: 30
      start_period: 5s

  ms-nest:
    container_name: sale-safari-api
    hostname: sale-safari-api
    build:
      context: ./sale-safari-api
    ports:
      - "4747:4747"
    environment:
      - EUREKA_HOST=eureka-server
      - MONGO_URI=mongodb://root:nest@db-nest:27017/nest?authSource=admin
      - KEYCLOAK_AUTH_SERVER_URL=https://keycloak.mkadmi.tech/auth
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=nest-api
      - KEYCLOAK_CLIENT_SECRET=R59s4jf2laeYwjNvhk1UkucQMdhnnxej
    depends_on:
      eureka-server:
        condition: service_healthy
      db-nest:
        condition: service_healthy

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=useJDBCCompliantTimezoneShift
      - NEXTAUTH_URL=http://localhost:3000/api/auth
      - KEYCLOAK_URL=https://keycloak.mkadmi.tech/auth
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=nest-api
      - KEYCLOAK_CLIENT_SECRET=R59s4jf2laeYwjNvhk1UkucQMdhnnxej
      - NEXT_PUBLIC_NEST_API_URL=http://apigateway/API/
      - NEXT_PUBLIC_TICKETS_API_URL=http://apigateway/TICKETS/
      - NEXT_PUBLIC_CART_API_URL=http://apigateway/CARTMS/
      - NEXT_PUBLIC_DELIVERY_API_URL=http://apigateway/MSDELIVERY/

  ms-cart:
    container_name: Cart-MS
    build:
      context: ./Cart-MS
    ports:
      - "8086:8086"
    environment:
      - EUREKA_SERVICE_URL= http://eureka-server:8761/eureka
      - SPRING_PROFILES_ACTIVE= dev
      - SPRING_DATASOURCE_URL= jdbc:h2:mem:cartdb
    depends_on:
      eureka-server:
        condition: service_started

  ms-delivery:
    container_name: Delivery-MS
    build:
      context: ./Delivery_MS
    ports:
      - "8088:8088"
    environment:
      - EUREKA_SERVICE_URL= http://eureka-server:8761/eureka
      - SPRING_PROFILES_ACTIVE= dev
      - SPRING_DATASOURCE_URL= jdbc:h2:file:./saleSAFARI/Delivery_MS/src/main/java/com/example/delivery_ms/DataBase/deliverydb
    depends_on:
      eureka-server:
        condition: service_started

  ms-order:
    container_name: Order-MS
    build:
      context: ./OrdermMS
    ports:
      - "9001:9001"
    environment:
        - EUREKA_SERVICE_URL= http://eureka-server:8761/eureka
        - SPRING_PROFILES_ACTIVE= dev
        - SPRING_DATASOURCE_URL= jdbc:h2:mem:cartdb
    depends_on:
      eureka-server:
         condition: service_started

  candidats:
    container_name: candidats
    hostname: candidats
    image: "dockerms"
    build: .
    ports:
      - "9000:9000"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://root:@db-mysql:3306/markett?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      eureka-server:
        condition: service_started
      db-mysql:
        condition: service_healthy

  db-mysql:
    image: "mysql:5.6"
    hostname: db-mysql
    container_name: db-mysqll
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # -----------------------------------------
  # Eureka:
  #   container_name: eureka
  #   hostname: serviceregistry
  #   ports:
  #     - "8761:8761"
  #   image: "steeltoeoss/eureka-server"
  #   environment:
  #     - spring.datasource.url=jdbc:mysql://root:@db-mysql:3306/markett?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #     - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/



  # db-mysql:
  #   image: "mysql:5.6"
  #   hostname: db-mysql
  #   container_name: db-mysqll
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=true
  #   ports:
  #     - "3307:3306"
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10

  # Market:
  #   container_name: market
  #   hostname: market
  #   image: "marketms"
  #   build: Market_MS
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
  #     - spring.datasource.url=jdbc:mysql://root:@db-mysql:3306/markett?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=
  #   depends_on:
  #     Eureka:
  #       condition: service_started
  #     db-mysql:
  #       condition: service_healthy

  # candidats:
  #   container_name: candidats
  #   hostname: candidats
  #   image: "dockerms"
  #   build: .
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
  #     - spring.datasource.url=jdbc:mysql://root:@db-mysql:3306/markett?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=
  #   depends_on:
  #     Eureka:
  #       condition: service_started
  #     db-mysql:
  #       condition: service_healthy

  # mongo_db:
  #   container_name: db_container
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_db:/data/db
