version: "3.9"
services:
  Eureka:
    container_name: eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: "steeltoeoss/eureka-server"
    environment:
      - spring.datasource.url=jdbc:mysql://root:@db-mysql:3306/markett?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

  db-mysql:
    image: "mysql:5.6"

    container_name: db-mysqll
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  Market:
    container_name: market
    hostname: market
    image: "marketms"
    build: Market_MS
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://root:@db-mysql:3306/markett?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      Eureka:
        condition: service_started
      db-mysql:
        condition: service_healthy

  NodeJsApp:
    container_name: nodejs-app
    image: stripe-ms  # Use the image name you assigned when building the Node.js app
    ports:
      - "4000:4000"
    depends_on:
      Eureka:
        condition: service_started


